# Generated by Django 4.2 on 2024-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashed_pass', models.CharField(max_length=64)),
                ('is_premium', models.BooleanField(default=False)),
                ('we', models.CharField(max_length=255)),
            ],
        ),
    ]
