# Generated by Django 5.0.4 on 2024-05-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='we',
        ),
        migrations.AddField(
            model_name='customuser',
            name='salt',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
